### ISSUE TITLE
I can not run project.

### ISSUE THREAD

**Issue by Tonkungs** [Mirror-Protocol/terra-web-app#3]
> Debugger attached.
> yarn run v1.22.5
> $ react-scripts start
> Debugger attached.
> Debugger attached.
> Attempting to bind to HOST environment variable: local.mirror.finance
> If this was unintentional, check that you haven't mistakenly set it in your shell.
> Learn more here: https://cra.link/advanced-config
> 
> Could not find an open port at local.mirror.finance.
> Network error message: listen EADDRNOTAVAIL: address not available 76.76.21.21
> 
> Waiting for the debugger to disconnect...
> Waiting for the debugger to disconnect...
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> Waiting for the debugger to disconnect...

I think because local.mirror.finance is down.

node : v12.13.0
yarn :  v1.22.5

**Comment by simcheolhwan** [comment]
Add the following entry to your `/etc/hosts` file:
​
```
127.0.0.1 local.mirror.finance
```
